# Generated by Django 2.0.3 on 2018-11-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerDecider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday', models.CharField(max_length=128)),
                ('Tuesday', models.CharField(max_length=128)),
                ('Wednesday', models.CharField(max_length=128)),
                ('Thursday', models.CharField(max_length=128)),
                ('Friday', models.CharField(max_length=128)),
                ('Saturday', models.CharField(max_length=128)),
                ('Sunday', models.CharField(max_length=128)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=128)),
                ('Due', models.DateField()),
                ('Info', models.TextField(max_length=1024, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
